bash:
    src: bashrc
    dst: ~/.bashrc

vim:
    src: vim.rc
    dst: ~/.vimrc

gitconfig:
    src: gitconfig
    dst: ~/.gitconfig

gitignore:
    src: gitignore
    src: ~/.gitignore

tmux:
    src: tmux.conf
    dst: ~/.tmux.conf

ssh:
    src: sshconfig
    dst: ~/.ssh/config
