bash:
    src: bashrc
    dst: ~/.bashrc

vim:
    src: vimrc
    dst: ~/.vimrc

tmux:
    src: tmux.conf
    dst: ~/.tmux.conf

ssh:
    src: sshconfig
    dst: ~/.ssh/config

gitconfig:
    src: gitconfig
    dst: ~/.gitconfig

gitignore:
    src: gitignore
    dst: ~/.gitignore

gitcompletion:
    src: git-completion.sh
    dst: ~/scripts/git-completion.sh

gitprompt:
    src: git-prompt.sh
    dst: ~/scripts/git-prompt.sh
