bash:
    src: bashrc
    dst: ~/.bashrc

vim:
    src: vimrc
    dst: ~/.vimrc

tmux:
    src: tmux.conf
    dst: ~/.tmux.conf

conky:
    src: conkyrc
    dst: ~/.conkyrc

ssh:
    src: sshconfig
    dst: ~/.ssh/config

gitconfig:
    src: gitconfig
    dst: ~/.gitconfig

gitignore:
    src: gitignore
    dst: ~/.gitignore

scripts:
    src: scripts
    dst: ~/.scripts/